on:
  push:
    branches:
      - master


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
         - uses: actions/checkout@v3

         - name: 'Login to Docker hup'
           run: docker login --username ${{ secrets.DOCKER_ENGYYYY }} --password ${{ secrets.DOCKER_TOKEN }}
         - name: 'Building docker image'
           run: docker build -t ${{ secrets.DOCKER_ENGYYYY }}/taskimage .

         - name: 'pushing to docker hup'
           run: docker push ${{ secrets.DOCKER_ENGYYYY }}/taskimage


